const config = {
  bookmarks: [
    {
      id: 1,
      title: "ChatGPT",
      url: "https://chatgpt.com",
      category: "AI",
      icon: "./icons/chatgpt-eex17e9e.ico",
      bgColor: "#ffffff",
    },
    {
      id: 2,
      title: "Grok",
      url: "https://grok.com/",
      category: "AI",
      icon: "./icons/grok-favicon-dark.png",
    },
    {
      id: 3,
      title: "Gemini",
      url: "https://gemini.google.com/app",
      category: "AI",
      icon: "./icons/gemini-favicon.svg",
    },
    {
      id: 4,
      title: "DeepSeek",
      url: "https://chat.deepseek.com/",
      category: "AI",
      icon: "https://chat.deepseek.com/favicon.svg",
    },
    {
      id: 5,
      title: "React Docs",
      url: "https://zh-hans.react.dev",
      category: "React",
      icon: "https://zh-hans.react.dev/favicon-32x32.png",
    },
    {
      id: 6,
      title: "TypeScript Docs",
      url: "https://www.typescriptlang.org",
      category: "文档",
      icon: "https://www.typescriptlang.org/favicon-32x32.png",
    },
    {
      id: 7,
      title: "MDN Web Docs",
      url: "https://developer.mozilla.org/zh-CN/",
      category: "文档",
      icon: "https://developer.mozilla.org/favicon.svg",
    },
    {
      id: 8,
      title: "Github Docs",
      url: "https://docs.github.com/zh",
      category: "文档",
      icon: "https://docs.github.com/assets/cb-345/images/site/favicon.png",
    },
    {
      id: 9,
      title: "NPM Docs",
      url: "https://docs.npmjs.com/",
      category: "文档",
      icon: "./icons/npm-b0f1a8318363185cc2ea6a40ac23eeb2.png",
    },
    {
      id: 10,
      title: "Node.js",
      url: "https://nodejs.org/docs/latest/api/",
      category: "Node.js",
      icon: "https://nodejs.org/static/images/favicons/favicon.png",
    },
    {
      id: 11,
      title: "Git Docs",
      url: "https://git-scm.com/docs",
      category: "文档",
      icon: "https://git-scm.com/favicon.ico",
    },
    {
      id: 12,
      title: "Webpack Docs",
      url: "https://webpack.docschina.org/concepts/",
      category: "文档",
      icon: "./icons/webpack-f326220248556af65f41.ico",
    },
    {
      id: 13,
      title: "Nginx",
      url: "https://nginx.org/en/docs/",
      category: "环境",
      icon: "https://nginx.org/favicon.ico",
    },
    {
      id: 14,
      title: "Docker",
      url: "https://www.docker.com/",
      category: "环境",
      icon: "https://www.docker.com/app/uploads/2024/02/cropped-docker-logo-favicon-32x32.png",
      bgColor: "#ffffff",
    },
    {
      id: 15,
      title: "GitHub",
      url: "https://github.com",
      category: "社区",
      icon: "https://github.githubassets.com/favicons/favicon-dark.svg",
    },
    {
      id: 16,
      title: "NPM",
      url: "https://www.npmjs.com/",
      category: "社区",
      icon: "./icons/npm-b0f1a8318363185cc2ea6a40ac23eeb2.png",
    },
    {
      id: 17,
      title: "Docker Hub",
      url: "https://hub.docker.com/",
      category: "社区",
      icon: "https://hub.docker.com/favicon.ico",
      bgColor: "#ffffff",
    },
    {
      id: 18,
      title: "Gitee",
      url: "https://gitee.com/explore",
      category: "社区",
      icon: "./icons/gitee-9007bd527d8a7851c8330e783151df58.ico",
    },
    {
      id: 19,
      title: "Product Hunt",
      url: "https://www.producthunt.com/",
      category: "社区",
      icon: "./icons/ph-favicon-brand-500.ico",
    },
    {
      id: 20,
      title: "图灵",
      url: "https://www.ituring.com.cn/",
      category: "社区",
      icon: "https://www.ituring.com.cn/favicon.png",
    },
    {
      id: 21,
      title: "Medium",
      url: "https://medium.com/",
      category: "社区",
      icon: "./icons/medium-favicon.png",
    },
    {
      id: 22,
      title: "知乎",
      url: "https://zhihu.com",
      category: "资讯",
      icon: "https://static.zhihu.com/heifetz/favicon.ico",
    },
    {
      id: 23,
      title: "掘金",
      url: "https://juejin.cn",
      category: "资讯",
      icon: "./icons/juejin-favicon.svg",
    },
    {
      id: 24,
      title: "腾讯云 Developers",
      url: "https://cloud.tencent.com/developer",
      category: "社区",
      icon: "https://cloud.tencent.com/favicon.ico",
    },
    {
      id: 25,
      title: "阿里云 Developers",
      url: "https://developer.aliyun.com/",
      category: "社区",
      icon: "./icons/aliyun-32-32.ico",
    },
    {
      id: 26,
      title: "微软 Developers",
      url: "https://learn.microsoft.com/zh-cn/",
      category: "社区",
      icon: "https://learn.microsoft.com/favicon.ico",
    },
    {
      id: 27,
      title: "谷歌 Developers",
      url: "https://developers.googleblog.com/",
      category: "社区",
      icon: "./icons/google-favicon.ico",
    },
    {
      id: 28,
      title: "W3C",
      url: "https://www.w3.org/zh-hans/",
      category: "社区",
      icon: "./icons/w3c-favicon-32.png",
    },
    {
      id: 29,
      title: "Stack Overflow",
      url: "https://stackoverflow.com/",
      category: "社区",
      icon: "./icons/StackOverflow-favicon.ico",
    },
    {
      id: 30,
      title: "微博",
      url: "https://weibo.com/",
      category: "资讯",
      icon: "https://weibo.com/favicon.ico",
    },
    {
      id: 31,
      title: "Bilibili",
      url: "https://www.bilibili.com/",
      category: "视频",
      icon: "./icons/bilibili-favicon.ico",
    },
    {
      id: 32,
      title: "YouTube",
      url: "https://www.youtube.com/",
      category: "视频",
      icon: "./icons/youtube-favicon.ico",
    },
    {
      id: 33,
      title: "极客时间",
      url: "https://time.geekbang.org",
      category: "视频",
      icon: "./icons/geekbang-favicon-32x32.webp",
    },
    {
      id: 34,
      title: "X",
      url: "https://x.com",
      category: "资讯",
      icon: "./icons/twitter.3.ico",
    },
    {
      id: 35,
      title: "语雀",
      url: "https://www.yuque.com",
      category: "笔记",
      icon: "./icons/original.png",
    },
    {
      id: 36,
      title: "V8 Docs",
      url: "https://v8.dev/",
      category: "文档",
      icon: "https://v8.dev/favicon.png",
    },
    {
      id: 37,
      title: "代码在线调试",
      url: "https://zhengjialux.github.io/Entry/CodePlayground/",
      category: "工具",
      icon: "https://zhengjialux.github.io./icons/JPCodePlayground.svg",
    },
    {
      id: 38,
      title: "百宝箱",
      url: "https://zhengjialux.github.io/Entry/KeyPreview/",
      category: "工具",
      icon: "https://zhengjialux.github.io./icons/KeyPreview.svg",
    },
    {
      id: 39,
      title: "图片处理",
      url: "https://zhengjialux.github.io/Entry/ImageAIProcessing/",
      category: "工具",
      icon: "https://zhengjialux.github.io./icons/ImageAIProcessing.png",
    },
    {
      id: 40,
      title: "颜色选择器",
      url: "https://zhengjialux.github.io/Entry/ColorPanel/",
      category: "工具",
      icon: "https://zhengjialux.github.io./icons/ColorPanel.svg",
    },
    {
      id: 41,
      title: "坐标拾取器",
      url: "https://lbs.baidu.com/maptool/getpoint",
      category: "工具",
      icon: "./icons/baidu-statics_logo_lbslogo_icon.ico",
    },
    {
      id: 42,
      title: "中国色",
      url: "https://zhongguose.com/",
      category: "工具",
      icon: "https://zhongguose.com/favicon.ico",
    },
    {
      id: 43,
      title: "Apizza",
      url: "https://www.apizza.net/",
      category: "工具",
      icon: "https://www.apizza.net/favicon.ico",
    },
    {
      id: 44,
      title: "D3",
      url: "https://d3js.org/",
      category: "D3",
      icon: "https://d3js.org/logo.svg",
    },
    {
      id: 45,
      title: "Three.js",
      url: "https://threejs.org/",
      category: "Three.js",
      icon: "https://threejs.org/files/favicon_white.ico",
    },
    {
      id: 46,
      title: "Vite",
      url: "https://cn.vitejs.dev/",
      category: "Vue",
      icon: "https://cn.vitejs.dev/logo.svg",
    },
    {
      id: 47,
      title: "Nuxt",
      url: "https://nuxt.com/",
      category: "Vue",
      icon: "https://nuxt.com/icon.png",
    },
    {
      id: 48,
      title: "Vue",
      url: "https://cn.vuejs.org/",
      category: "Vue",
      icon: "https://cn.vuejs.org/logo.svg",
    },
    {
      id: 49,
      title: "Pinia",
      url: "https://pinia.vuejs.org/zh/",
      category: "Vue",
      icon: "https://pinia.vuejs.org/logo.png",
    },
    {
      id: 50,
      title: "Vue Router",
      url: "https://router.vuejs.org/zh/",
      category: "Vue",
      icon: "https://router.vuejs.org/logo.svg",
    },
    {
      id: 51,
      title: "Next.js",
      url: "https://nextjs.org/",
      category: "React",
      icon: "https://nextjs.org/favicon.ico",
    },
    {
      id: 52,
      title: "React Native",
      url: "https://reactnative.cn/",
      category: "React",
      icon: "https://reactnative.cn/img/favicon.ico",
    },
    {
      id: 53,
      title: "Redux",
      url: "https://redux.js.org",
      category: "React",
      icon: "https://redux.js.org/img/favicon/favicon.ico",
    },
    {
      id: 54,
      title: "React Router",
      url: "https://reactrouter.com/home",
      category: "React",
      icon: "https://reactrouter.com/favicon-dark.png",
    },
    {
      id: 55,
      title: "MobX",
      url: "https://mobx.js.org/",
      category: "React",
      icon: "https://mobx.js.org/img/favicon.png",
    },
    {
      id: 56,
      title: "Express",
      url: "https://expressjs.com/zh-cn/",
      category: "Node.js",
      icon: "https://expressjs.com/images/favicon.png",
    },
    {
      id: 57,
      title: "Koa",
      url: "https://koa.bootcss.com/",
      category: "Node.js",
      icon: "https://koa.bootcss.com/public/images/koa-logo.png",
    },
    {
      id: 58,
      title: "Umi.js",
      url: "https://umijs.org/",
      category: "React",
      icon: "./icons/umi-k7bjua9c_w132_h130.png",
    },
    {
      id: 59,
      title: "Qiankun",
      url: "https://qiankun.umijs.org/zh",
      category: "跨终端框架",
      icon: "./icons/qiankun-km0cv8vn_w500_h500.png",
    },
    {
      id: 60,
      title: "Vuex",
      url: "https://vuex.vuejs.org/zh/",
      category: "Vue",
      icon: "https://vuex.vuejs.org/logo.png",
    },
    {
      id: 61,
      title: "uni-app",
      url: "https://uniapp.dcloud.net.cn/",
      category: "跨终端框架",
      icon: "./icons/uni-icon.png",
    },
    {
      id: 62,
      title: "微信小程序",
      url: "https://mp.weixin.qq.com/",
      category: "跨终端框架",
      icon: "./icons/wx.ico",
    },
    {
      id: 63,
      title: "Electron",
      url: "https://www.electronjs.org/zh/",
      category: "跨终端框架",
      icon: "https://www.electronjs.org/zh/assets/img/favicon.ico",
    },
    {
      id: 64,
      title: "Flutter",
      url: "https://docs.flutter.dev/",
      category: "跨终端框架",
      icon: "./icons/flutter-favicon.svg",
    },
    {
      id: 65,
      title: "Flutter Docs",
      url: "https://docs.flutter.cn/community/china/",
      category: "文档",
      icon: "./icons/flutter-docs.svg",
    },
    {
      id: 66,
      title: "Tauri",
      url: "https://tauri.app/zh-cn/",
      category: "跨终端框架",
      icon: "https://tauri.app/logo.png",
    },
    {
      id: 67,
      title: "Taro Docs",
      url: "https://docs.taro.zone/docs/",
      category: "文档",
      icon: "https://docs.taro.zone/img/logo-taro.png",
    },
    {
      id: 68,
      title: "MySQL Docs",
      url: "https://dev.mysql.com/doc/refman/8.0/en/",
      category: "数据库",
      icon: "./icons/mysql-favicon.ico",
    },
    {
      id: 69,
      title: "PostgreSQL Docs",
      url: "https://www.postgresql.org/docs/",
      category: "数据库",
      icon: "https://www.postgresql.org/favicon.ico",
    },
    {
      id: 70,
      title: "Redis",
      url: "https://redis.io/",
      category: "数据库",
      icon: "https://redis.io/favicon.ico",
    },
    {
      id: 71,
      title: "Elasticsearch",
      url: "https://www.elastic.co/elasticsearch",
      category: "数据库",
      icon: "https://www.elastic.co/icon-192.png",
    },
    {
      id: 72,
      title: "MongoDB",
      url: "https://www.mongodb.com/zh-cn/docs/",
      category: "数据库",
      icon: "./icons/mongodb-favicon.ico",
    },
    {
      id: 73,
      title: "Python Docs",
      url: "https://docs.python.org/zh-cn/3.9/c-api/index.html",
      category: "Python",
      icon: "https://docs.python.org/zh-cn/3.9/_static/py.svg",
    },
    {
      id: 74,
      title: "PyPI",
      url: "https://pypi.org/",
      category: "Python",
      icon: "https://pypi.org/static/images/favicon.35549fe8.ico",
    },
    {
      id: 75,
      title: "Angular Docs",
      url: "https://angular.cn/overview",
      category: "Angular",
      icon: "./icons/angular-favicon.ico",
    },
    {
      id: 76,
      title: "Ngrx Docs",
      url: "https://ngrx.io/",
      category: "Angular",
      icon: "https://ngrx.io/favicon-32x32.png",
    },
    {
      id: 77,
      title: "Material Docs",
      url: "https://material.angular.dev/",
      category: "Angular",
      icon: "https://material.angular.dev/assets/img/favicon.ico",
    },
    {
      id: 78,
      title: "OpenResty",
      url: "https://openresty.org/cn/",
      category: "环境",
      icon: "https://openresty.org/favicon.ico",
    },
    {
      id: 79,
      title: "Jenkins",
      url: "https://www.jenkins.io/",
      category: "环境",
      icon: "https://www.jenkins.io/favicon.ico",
    },
    {
      id: 80,
      title: "宝塔面板",
      url: "https://www.bt.cn/new/index.html",
      category: "环境",
      icon: "./icons/bt-favicon.ico",
    },
    {
      id: 81,
      title: "Three.js Docs",
      url: "https://techbrood.com/threejs/docs/",
      category: "Three.js",
      icon: "https://techbrood.com/favicon.ico",
    },
    {
      id: 82,
      title: "Mobx-State-Tree",
      url: "https://mobx-state-tree.js.org/intro/welcome",
      category: "React",
      icon: "https://mobx-state-tree.js.org/img/favicon.ico",
    },
    {
      id: 83,
      title: "D3.js 图形库",
      url: "https://d3-graph-gallery.com/all.html",
      category: "D3",
      icon: "",
    },
    {
      id: 84,
      title: "ObservableHQ",
      url: "https://observablehq.com/top",
      category: "D3",
      icon: "./icons/observablehq-favicon.png",
      bgColor: "#ffffff",
    },
    {
      id: 85,
      title: "D3.js 深度解析",
      url: "https://www.d3indepth.com/",
      category: "D3",
      icon: "./icons/d3indepth-favicon.png",
    },
    {
      id: 86,
      title: "AntV G2",
      url: "https://g2.antv.antgroup.com/",
      category: "D3",
      icon: "./icons/g2-original.png",
    },
    {
      id: 87,
      title: "Echarts",
      url: "https://echarts.apache.org/zh/index.html",
      category: "D3",
      icon: "https://echarts.apache.org/zh/images/favicon.png",
    },
    {
      id: 88,
      title: "Element",
      url: "https://element.eleme.cn/#/zh-CN",
      category: "Vue",
      icon: "https://element.eleme.cn/favicon.ico",
    },
    {
      id: 89,
      title: "Ant Design",
      url: "https://ant-design.antgroup.com/index-cn",
      category: "React",
      icon: "./icons/antd-favicon.svg",
    },
    {
      id: 90,
      title: "Axios",
      url: "https://axios-http.com/zh/",
      category: "文档",
      icon: "https://axios-http.com/assets/favicon.ico",
    },
    {
      id: 91,
      title: "Sass",
      url: "https://www.sass.hk/",
      category: "文档",
      icon: "https://www.sass.hk/favicon.ico",
    },
    {
      id: 92,
      title: "Less",
      url: "https://lesscss.org/",
      category: "文档",
      icon: "https://lesscss.org/public/ico/favicon.ico",
    },
    {
      id: 93,
      title: "Tailwind CSS",
      url: "https://tailwindcss.com/",
      category: "文档",
      icon: "https://tailwindcss.com/favicons/favicon.ico",
    },
    {
      id: 94,
      title: "Markdown",
      url: "https://markdown.com.cn/",
      category: "文档",
      icon: "https://markdown.com.cn/favicon.ico",
      bgColor: "#ffffff",
    },
    {
      id: 95,
      title: "v0.app",
      url: "https://v0.app/",
      category: "文档",
      icon: "./icons/v0-favicon.svg",
    },
    {
      id: 96,
      title: "LeetCode",
      url: "https://leetcode.cn/",
      category: "社区",
      icon: "https://leetcode.cn/favicon.ico",
    },
    {
      id: 97,
      title: "Day.js",
      url: "https://day.js.org/zh-CN/",
      category: "文档",
      icon: "https://day.js.org/img/logo.png",
    },
    {
      id: 98,
      title: "Mock.js",
      url: "http://mockjs.com/",
      category: "文档",
      icon: "./icons/mock-favicon.svg",
    },
    {
      id: 99,
      title: "jQuery",
      url: "https://api.jquery.com/",
      category: "文档",
      icon: "./icons/jq-favicon.ico",
    },
    {
      id: 100,
      title: "jQuery 中文文档",
      url: "http://caibaojian.com/jquery/",
      category: "文档",
      icon: "./icons/jqcn-favicon.ico",
    },
    {
      id: 101,
      title: "Shadowsocks",
      url: "https://portal.shadowsocks.nz/",
      category: "VPN",
      icon: "https://portal.shadowsocks.nz/favicon.ico",
    },
    {
      id: 102,
      title: "一元机场",
      url: "https://xn--1-q07a56pdss.com/#/profile",
      category: "VPN",
      icon: "https://xn--1-q07a56pdss.com/favicon.ico",
    },
    {
      id: 103,
      title: "163 邮箱",
      url: "https://email.163.com/",
      category: "Email",
      icon: "https://email.163.com/favicon.ico",
    },
    {
      id: 104,
      title: "QQ 邮箱",
      url: "https://mail.qq.com/",
      category: "Email",
      icon: "./icons/email.app.3c368bb.png",
    },
    {
      id: 105,
      title: "阿里云企业邮箱",
      url: "https://qiye.aliyun.com/",
      category: "Email",
      icon: "./icons/aliyun-email-favicon.ico",
    },
    {
      id: 106,
      title: "Gmail",
      url: "https://mail.google.com/",
      category: "Email",
      icon: "./icons/gmail.ico",
    },
    {
      id: 107,
      title: "阿里云",
      url: "https://www.aliyun.com/",
      category: "cloud",
      icon: "./icons/aliyun-32-32.ico",
    },
    {
      id: 108,
      title: "腾讯云",
      url: "https://cloud.tencent.com/",
      category: "cloud",
      icon: "https://cloud.tencent.com/favicon.ico",
    },
    {
      id: 109,
      title: "有道云笔记",
      url: "https://note.youdao.com/",
      category: "笔记",
      icon: "https://note.youdao.com/favicon.ico",
    },
    {
      id: 110,
      title: "Visual Studio Code",
      url: "https://code.visualstudio.com/",
      category: "IDE",
      icon: "https://code.visualstudio.com/assets/favicon.ico",
    },
    {
      id: 111,
      title: "Cloud Copilot",
      url: "https://copilot.tencent.com/ide/",
      category: "IDE",
      icon: "./icons/copilot-logo.svg",
    },
    {
      id: 112,
      title: "Cursor",
      url: "https://cursor.com/cn",
      category: "IDE",
      icon: "https://cursor.com/marketing-static/favicon.ico",
    },
    {
      id: 113,
      title: "Trae",
      url: "https://www.trae.cn/",
      category: "IDE",
      icon: "./icons/trae-favicon.png",
    },
    {
      id: 114,
      title: "CodeParrot",
      url: "https://codeparrot.ai/",
      category: "UI",
      icon: "https://codeparrot.ai/logo.svg",
    },
    {
      id: 115,
      title: "Figma",
      url: "https://www.figma.com/",
      category: "UI",
      icon: "https://static.figma.com/app/icon/1/favicon.ico",
    },
    {
      id: 116,
      title: "通义灵码",
      url: "https://lingma.aliyun.com/",
      category: "IDE",
      icon: "./icons/lingma.png",
    },
    {
      id: 117,
      title: "Qodo",
      url: "https://www.qodo.ai/",
      category: "IDE",
      icon: "./icons/qodo-fav-32x32.webp",
    },
    {
      id: 118,
      title: "Claude",
      url: "https://claude.com/",
      category: "IDE",
      icon: "./icons/claude-favicon.png",
    },
    {
      id: 119,
      title: "Jest",
      url: "https://jestjs.io/",
      category: "文档",
      icon: "https://jestjs.io/img/favicon/favicon.ico",
    },
    {
      id: 120,
      title: "即时设计",
      url: "https://js.design/",
      category: "UI",
      icon: "https://img.js.design/assets/webImg/favicon.ico",
    },
    {
      id: 121,
      title: "Uizard",
      url: "https://app.uizard.io/",
      category: "UI",
      icon: "./icons/uizard-favicon-32x32.png",
    },
    {
      id: 122,
      title: "Stitch",
      url: "https://stitch.withgoogle.com/",
      category: "UI",
      icon: "./icons/stitch-favicon-32x32.png",
    },
    {
      id: 123,
      title: "墨刀",
      url: "https://modao.cc/brand",
      category: "UI",
      icon: "https://images.modao.cc/images/favicon.ico",
    },
    {
      id: 124,
      title: "GitHub Copilot",
      url: "https://github.com/features/copilot",
      category: "IDE",
      icon: "./icons/copilot-favicon.svg",
    },
    {
      id: 125,
      title: "IKuuu",
      url: "https://ikuuu.de/",
      category: "VPN",
      icon: "./icons/ikuuu-favicon.svg",
    },
    {
      id: 126,
      title: "百度地图",
      url: "https://lbsyun.baidu.com/",
      category: "GIS",
      icon: "./icons/baidu-statics_logo_lbslogo_icon.ico",
    },
    {
      id: 127,
      title: "高德地图",
      url: "https://lbs.amap.com/demo/list/js-api",
      category: "GIS",
      icon: "https://a.amap.com/pc/static/favicon.ico",
    },
    {
      id: 128,
      title: "AntV L7",
      url: "https://l7.antv.antgroup.com/tutorial/quickstart",
      category: "GIS",
      icon: "./icons/g2-original.png",
    },
    {
      id: 129,
      title: "Mapbox",
      url: "https://www.mapbox.com/",
      category: "GIS",
      icon: "./icons/mapbox_favicon_32x32.png",
    },
    {
      id: 130,
      title: "Deck.gl",
      url: "https://deck.gl/",
      category: "GIS",
      icon: "./icons/geck.gl-favicon.ico",
    },
    {
      id: 131,
      title: "React AMap",
      url: "https://elemefe.github.io/react-amap/",
      category: "GIS",
      icon: "./icons/el-map-favicon.png",
    },
    {
      id: 132,
      title: "Natural Earth",
      url: "https://www.naturalearthdata.com/",
      category: "GIS",
      icon: "",
    },
    {
      id: 133,
      title: "PM2",
      url: "https://pm2.io/docs/plus/overview/",
      category: "工具",
      icon: "https://pm2.io/favicon.ico",
      bgColor: "#ffffff",
    },
    {
      id: 134,
      title: "Wireshark",
      url: "https://www.wireshark.org/",
      category: "工具",
      icon: "https://www.wireshark.org/favicon.ico",
    },
    {
      id: 135,
      title: "Termius",
      url: "https://termius.com/index.html",
      category: "工具",
      icon: "./icons/termius-p7fs9iEFzckw8YZe84MoQfRQ.avif",
    },
    {
      id: 136,
      title: "Postman",
      url: "https://www.postman.com/",
      category: "工具",
      icon: "./icons/postman-favicon.svg",
    },
    {
      id: 137,
      title: "iTerm2",
      url: "https://iterm2.com/",
      category: "工具",
      icon: "https://iterm2.com/favicon.ico",
    },
    {
      id: 138,
      title: "Oh My Zsh",
      url: "https://ohmyz.sh/",
      category: "工具",
      icon: "https://ohmyz.sh/favicon.ico",
    },
    {
      id: 139,
      title: "Oh My Posh",
      url: "https://ohmyposh.dev/",
      category: "工具",
      icon: "https://ohmyposh.dev/img/favicons.svg",
    },
    {
      id: 140,
      title: "Openvpn Connect",
      url: "https://openvpn.net/client/",
      category: "工具",
      icon: "./icons/openvpn-favicon.ico",
    },
    {
      id: 141,
      title: "HexHub",
      url: "https://www.hexhub.cn/",
      category: "工具",
      icon: "https://www.hexhub.cn/favicon.ico",
    },
    {
      id: 142,
      title: "Cherry AI",
      url: "https://www.cherry-ai.com/",
      category: "工具",
      icon: "./icons/cherry-favicon.png",
    },
    {
      id: 143,
      title: "GitButler",
      url: "https://gitbutler.com/",
      category: "工具",
      icon: "https://gitbutler.com/favicon/favicon.svg",
    },
    {
      id: 144,
      title: "Draw.io",
      url: "https://www.drawio.com/",
      category: "工具",
      icon: "https://www.drawio.com/favicon.ico",
    },
    {
      id: 145,
      title: "SwitchHosts",
      url: "https://switchhosts.vercel.app/zh",
      category: "工具",
      icon: "./icons/switchhosts-favicon.ico",
    },
    {
      id: 146,
      title: "Gitea",
      url: "https://about.gitea.com/",
      category: "工具",
      icon: "https://about.gitea.com/gitea.svg",
    },
    {
      id: 147,
      title: "Babel",
      url: "https://www.babeljs.cn/",
      category: "文档",
      icon: "https://www.babeljs.cn/img/favicon.png",
    },
    {
      id: 148,
      title: "MasterGo",
      url: "https://mastergo.com/",
      category: "工具",
      icon: "https://mastergo.com/favicon.ico",
    },
    {
      id: 149,
      title: "菜鸟教程",
      url: "https://www.runoob.com/",
      category: "社区",
      icon: "./icons/runoob-favicon.ico",
    },
    {
      id: 150,
      title: "W3Cschool",
      url: "https://www.w3cschool.cn/",
      category: "社区",
      icon: "./icons/w3cschool-favicon.ico",
    },
    {
      id: 151,
      title: "牛客网",
      url: "https://www.nowcoder.com/",
      category: "社区",
      icon: "./icons/nowcoderfavicon.ico",
    },
    {
      id: 152,
      title: "Qoder",
      url: "https://qoder.com/",
      category: "IDE",
      icon: "./icons/qoder-favicon.svg",
    },
    {
      id: 153,
      title: "Antigravity",
      url: "https://antigravity.google/",
      category: "IDE",
      icon: "./icons/antigravity-logo.png",
    },
    {
      id: 154,
      title: "Hoppscotch",
      url: "https://hoppscotch.io/",
      category: "工具",
      icon: "./icons/hoppscotch-192x192.png",
    },
    {
      id: 155,
      title: "Sublime Text",
      url: "https://www.sublimetext.com/",
      category: "IDE",
      icon: "https://www.sublimetext.com/favicon.ico",
    },
    {
      id: 156,
      title: "GoAnother",
      url: "https://goanother.com/cn/",
      category: "工具",
      icon: "https://goanother.com/favicon.ico",
    },
    {
      id: 157,
      title: "SourceTree",
      url: "https://www.sourcetreeapp.com/",
      category: "工具",
      icon: "./icons/sourcetree-favicon.ico",
    },
    {
      id: 158,
      title: "HBuilderX",
      url: "https://www.dcloud.io/hbuilderx.html",
      category: "工具",
      icon: "https://hx.dcloud.net.cn/static/favicon/favicon.png",
    },
    {
      id: 159,
      title: "Google Chrome",
      url: "https://www.google.cn/chrome/index.html",
      category: "工具",
      icon: "./icons/chrome-favicon-32x32.png",
    },
    {
      id: 160,
      title: "Firefox",
      url: "https://www.firefox.com/zh-CN/",
      category: "工具",
      icon: "./icons/firefox-favicon.f093404c0135.ico",
    },
    {
      id: 161,
      title: "Navicat",
      url: "https://www.navicat.com.cn/",
      category: "工具",
      icon: "./icons/Navicat_16_Premium_win_256x256.ico",
    },
    {
      id: 162,
      title: "WPS",
      url: "https://platform.wps.cn/",
      category: "工具",
      icon: "./icons/wps-favicon.ico",
    },
    {
      id: 163,
      title: "IntelliJ IDEA",
      url: "https://www.jetbrains.com/idea/download/",
      category: "IDE",
      icon: "./icons/Idea-Dark.svg",
    },
    {
      id: 164,
      title: "DataGrip",
      url: "https://www.jetbrains.com/datagrip/download/",
      category: "IDE",
      icon: "https://www.jetbrains.com/favicon.ico",
    },
    {
      id: 165,
      title: "PyCharm",
      url: "https://www.jetbrains.com/pycharm/download/",
      category: "IDE",
      icon: "./icons/PyCharm-Dark.svg",
    },
    {
      id: 166,
      title: "CLion",
      url: "https://www.jetbrains.com/clion/download/",
      category: "IDE",
      icon: "./icons/CLion-Dark.svg",
    },
    {
      id: 167,
      title: "GoLand",
      url: "https://www.jetbrains.com/go/download/",
      category: "IDE",
      icon: "https://www.jetbrains.com/favicon.ico",
    },
    {
      id: 168,
      title: "WebStorm",
      url: "https://www.jetbrains.com/webstorm/download/",
      category: "IDE",
      icon: "./icons/WebStorm-Dark.svg",
    },
    {
      id: 169,
      title: "Yarn",
      url: "https://yarnpkg.com/",
      category: "工具",
      icon: "https://yarnpkg.com/img/yarn-favicon.svg",
    },
    {
      id: 170,
      title: "pnpm",
      url: "https://pnpm.io/zh/",
      category: "工具",
      icon: "https://pnpm.io/zh/img/favicon.png",
    },
    {
      id: 171,
      title: "OPM",
      url: "https://opm.openresty.org/",
      category: "工具",
      icon: "https://openresty.org/favicon.ico",
    },
    {
      id: 172,
      title: "MongoDB 中文社区",
      url: "https://mongoing.com/",
      category: "社区",
      icon: "./icons/mongoing-favicon.ico",
    },
    {
      id: 173,
      title: "Moment.js",
      url: "https://momentjs.com/",
      category: "工具",
      icon: "./icons/moment-favicon.png",
    }
  ],
  categoryIcons: {
    all: "📚",
    视频: "🎬",
    音乐: "🎵",
    工具: "🔧",
    其他: "📁",
    资讯: "📰",
    社区: "💬",
    环境: "🌍",
    文档: "📖",
    AI: "🤖",
    笔记: "📝",
    数据库: "🗄️",
    IDE: "💻",
    Python: "🐍",
    Angular: "🦄",
    跨终端框架: "🌐",
    Vue: "🍃",
    React: "⚛️",
    "Node.js": "🖥️",
    D3: "📊",
    "Three.js": "🧊",
    VPN: "🔒",
    Email: "📧",
    cloud: "☁️",
    UI: "🎨",
    GIS: "🗺️",
  },
};
