const config = {
  bookmarks: [
    {
      title: "ChatGPT",
      url: "https://chatgpt.com",
      category: "AI",
      icon: "./icons/chatgpt-eex17e9e.ico",
      bgColor: "#ffffff",
    },
    {
      title: "Grok",
      url: "https://grok.com/",
      category: "AI",
      icon: "./icons/grok-favicon-dark.png",
    },
    {
      title: "Gemini",
      url: "https://gemini.google.com/app",
      category: "AI",
      icon: "./icons/gemini-favicon.svg",
    },
    {
      title: "DeepSeek",
      url: "https://chat.deepseek.com/",
      category: "AI",
      icon: "https://chat.deepseek.com/favicon.svg",
    },
    {
      title: "React Docs",
      url: "https://zh-hans.react.dev",
      category: "React",
      icon: "https://zh-hans.react.dev/favicon-32x32.png",
      Mark: true,
    },
    {
      title: "TypeScript Docs",
      url: "https://www.typescriptlang.org",
      category: "文档",
      icon: "https://www.typescriptlang.org/favicon-32x32.png",
      Mark: true,
    },
    {
      title: "MDN Web Docs",
      url: "https://developer.mozilla.org/zh-CN/",
      category: "文档",
      icon: "https://developer.mozilla.org/favicon.svg",
      Mark: true,
    },
    {
      title: "Github Docs",
      url: "https://docs.github.com/zh",
      category: "文档",
      icon: "https://docs.github.com/assets/cb-345/images/site/favicon.png",
    },
    {
      title: "NPM Docs",
      url: "https://docs.npmjs.com/",
      category: "文档",
      icon: "./icons/npm-b0f1a8318363185cc2ea6a40ac23eeb2.png",
    },
    {
      title: "Node.js",
      url: "https://nodejs.org/docs/latest/api/",
      category: "Node.js",
      icon: "https://nodejs.org/static/images/favicons/favicon.png",
      Mark: true,
    },
    {
      title: "Git Docs",
      url: "https://git-scm.com/docs",
      category: "文档",
      icon: "https://git-scm.com/favicon.ico",
      Mark: true,
    },
    {
      title: "Webpack Docs",
      url: "https://webpack.docschina.org/concepts/",
      category: "文档",
      icon: "./icons/webpack-f326220248556af65f41.ico",
      Mark: true,
    },
    {
      title: "Nginx",
      url: "https://nginx.org/en/docs/",
      category: "环境",
      icon: "https://nginx.org/favicon.ico",
      Mark: true,
    },
    {
      title: "Docker",
      url: "https://www.docker.com/",
      category: "环境",
      icon: "https://www.docker.com/app/uploads/2024/02/cropped-docker-logo-favicon-32x32.png",
      bgColor: "#ffffff",
      Mark: true,
    },
    {
      title: "GitHub",
      url: "https://github.com",
      category: "社区",
      icon: "https://github.githubassets.com/favicons/favicon-dark.svg",
      Mark: true,
    },
    {
      title: "NPM",
      url: "https://www.npmjs.com/",
      category: "社区",
      icon: "./icons/npm-b0f1a8318363185cc2ea6a40ac23eeb2.png",
      Mark: true,
    },
    {
      title: "Docker Hub",
      url: "https://hub.docker.com/",
      category: "社区",
      icon: "https://hub.docker.com/favicon.ico",
      bgColor: "#ffffff",
    },
    {
      title: "Gitee",
      url: "https://gitee.com/explore",
      category: "社区",
      icon: "./icons/gitee-9007bd527d8a7851c8330e783151df58.ico",
    },
    {
      title: "Product Hunt",
      url: "https://www.producthunt.com/",
      category: "社区",
      icon: "./icons/ph-favicon-brand-500.ico",
      Mark: true,
    },
    {
      title: "图灵",
      url: "https://www.ituring.com.cn/",
      category: "社区",
      icon: "https://www.ituring.com.cn/favicon.png",
    },
    {
      title: "Medium",
      url: "https://medium.com/",
      category: "社区",
      icon: "./icons/medium-favicon.png",
    },
    {
      title: "知乎",
      url: "https://zhihu.com",
      category: "资讯",
      icon: "https://static.zhihu.com/heifetz/favicon.ico",
    },
    {
      title: "掘金",
      url: "https://juejin.cn",
      category: "资讯",
      icon: "./icons/juejin-favicon.svg",
    },
    {
      title: "腾讯云 Developers",
      url: "https://cloud.tencent.com/developer",
      category: "社区",
      icon: "https://cloud.tencent.com/favicon.ico",
    },
    {
      title: "阿里云 Developers",
      url: "https://developer.aliyun.com/",
      category: "社区",
      icon: "./icons/aliyun-32-32.ico",
    },
    {
      title: "微软 Developers",
      url: "https://learn.microsoft.com/zh-cn/",
      category: "社区",
      icon: "https://learn.microsoft.com/favicon.ico",
    },
    {
      title: "谷歌 Developers",
      url: "https://developers.googleblog.com/",
      category: "社区",
      icon: "./icons/google-favicon.ico",
    },
    {
      title: "W3C",
      url: "https://www.w3.org/zh-hans/",
      category: "社区",
      icon: "./icons/w3c-favicon-32.png",
    },
    {
      title: "Stack Overflow",
      url: "https://stackoverflow.com/",
      category: "社区",
      icon: "./icons/StackOverflow-favicon.ico",
    },
    {
      title: "微博",
      url: "https://weibo.com/",
      category: "资讯",
      icon: "https://weibo.com/favicon.ico",
    },
    {
      title: "Bilibili",
      url: "https://www.bilibili.com/",
      category: "视频",
      icon: "./icons/bilibili-favicon.ico",
    },
    {
      title: "YouTube",
      url: "https://www.youtube.com/",
      category: "视频",
      icon: "./icons/youtube-favicon.ico",
    },
    {
      title: "极客时间",
      url: "https://time.geekbang.org",
      category: "视频",
      icon: "./icons/geekbang-favicon-32x32.webp",
    },
    {
      title: "X",
      url: "https://x.com",
      category: "资讯",
      icon: "./icons/twitter.3.ico",
    },
    {
      title: "语雀",
      url: "https://www.yuque.com",
      category: "笔记",
      icon: "./icons/original.png",
    },
    {
      title: "V8 Docs",
      url: "https://v8.dev/",
      category: "文档",
      icon: "https://v8.dev/favicon.png",
    },
    {
      title: "代码在线调试",
      url: "https://zhengjialux.github.io/Entry/CodePlayground/",
      category: "工具",
      icon: "https://zhengjialux.github.io/icons/JPCodePlayground.svg",
    },
    {
      title: "百宝箱",
      url: "https://zhengjialux.github.io/Entry/KeyPreview/",
      category: "工具",
      icon: "https://zhengjialux.github.io/icons/KeyPreview.svg",
    },
    {
      title: "图片处理",
      url: "https://zhengjialux.github.io/Entry/ImageAIProcessing/",
      category: "工具",
      icon: "https://zhengjialux.github.io/icons/ImageAIProcessing.png",
    },
    {
      title: "颜色选择器",
      url: "https://zhengjialux.github.io/Entry/ColorPanel/",
      category: "工具",
      icon: "https://zhengjialux.github.io/icons/ColorPanel.svg",
    },
    {
      title: "坐标拾取器",
      url: "https://lbs.baidu.com/maptool/getpoint",
      category: "工具",
      icon: "./icons/baidu-statics_logo_lbslogo_icon.ico",
    },
    {
      title: "中国色",
      url: "https://zhongguose.com/",
      category: "工具",
      icon: "https://zhongguose.com/favicon.ico",
    },
    {
      title: "Apizza",
      url: "https://www.apizza.net/",
      category: "工具",
      icon: "https://www.apizza.net/favicon.ico",
    },
    {
      title: "D3",
      url: "https://d3js.org/",
      category: "D3",
      icon: "https://d3js.org/logo.svg",
      Mark: true,
    },
    {
      title: "Three.js",
      url: "https://threejs.org/",
      category: "Three.js",
      icon: "https://threejs.org/files/favicon_white.ico",
      Mark: true,
    },
    {
      title: "Vite",
      url: "https://cn.vitejs.dev/",
      category: "Vue",
      icon: "https://cn.vitejs.dev/logo.svg",
      Mark: true,
    },
    {
      title: "Nuxt",
      url: "https://nuxt.com/",
      category: "Vue",
      icon: "https://nuxt.com/icon.png",
      Mark: true,
    },
    {
      title: "Vue",
      url: "https://cn.vuejs.org/",
      category: "Vue",
      icon: "https://cn.vuejs.org/logo.svg",
      Mark: true,
    },
    {
      title: "Pinia",
      url: "https://pinia.vuejs.org/zh/",
      category: "Vue",
      icon: "https://pinia.vuejs.org/logo.png",
    },
    {
      title: "Vue Router",
      url: "https://router.vuejs.org/zh/",
      category: "Vue",
      icon: "https://router.vuejs.org/logo.svg",
    },
    {
      title: "Next.js",
      url: "https://nextjs.org/",
      category: "React",
      icon: "https://nextjs.org/favicon.ico",
      Mark: true,
    },
    {
      title: "React Native",
      url: "https://reactnative.cn/",
      category: "React",
      icon: "https://reactnative.cn/img/favicon.ico",
      Mark: true,
    },
    {
      title: "Redux",
      url: "https://redux.js.org",
      category: "React",
      icon: "https://redux.js.org/img/favicon/favicon.ico",
    },
    {
      title: "React Router",
      url: "https://reactrouter.com/home",
      category: "React",
      icon: "https://reactrouter.com/favicon-dark.png",
    },
    {
      title: "MobX",
      url: "https://mobx.js.org/",
      category: "React",
      icon: "https://mobx.js.org/img/favicon.png",
    },
    {
      title: "Express",
      url: "https://expressjs.com/zh-cn/",
      category: "Node.js",
      icon: "https://expressjs.com/images/favicon.png",
      Mark: true,
    },
    {
      title: "Koa",
      url: "https://koa.bootcss.com/",
      category: "Node.js",
      icon: "https://koa.bootcss.com/public/images/koa-logo.png",
    },
    {
      title: "Umi.js",
      url: "https://umijs.org/",
      category: "React",
      icon: "./icons/umi-k7bjua9c_w132_h130.png",
      Mark: true,
    },
    {
      title: "Qiankun",
      url: "https://qiankun.umijs.org/zh",
      category: "跨终端框架",
      icon: "./icons/qiankun-km0cv8vn_w500_h500.png",
      Mark: true,
    },
    {
      title: "Vuex",
      url: "https://vuex.vuejs.org/zh/",
      category: "Vue",
      icon: "https://vuex.vuejs.org/logo.png",
    },
    {
      title: "uni-app",
      url: "https://uniapp.dcloud.net.cn/",
      category: "跨终端框架",
      icon: "./icons/uni-icon.png",
      Mark: true,
    },
    {
      title: "微信小程序",
      url: "https://mp.weixin.qq.com/",
      category: "跨终端框架",
      icon: "./icons/wx.ico",
      Mark: true,
    },
    {
      title: "Electron",
      url: "https://www.electronjs.org/zh/",
      category: "跨终端框架",
      icon: "https://www.electronjs.org/zh/assets/img/favicon.ico",
      Mark: true,
    },
    {
      title: "Flutter",
      url: "https://docs.flutter.dev/",
      category: "跨终端框架",
      icon: "./icons/flutter-favicon.svg",
    },
    {
      title: "Flutter Docs",
      url: "https://docs.flutter.cn/community/china/",
      category: "文档",
      icon: "./icons/flutter-docs.svg",
    },
    {
      title: "Tauri",
      url: "https://tauri.app/zh-cn/",
      category: "跨终端框架",
      icon: "https://tauri.app/logo.png",
    },
    {
      title: "Taro Docs",
      url: "https://docs.taro.zone/docs/",
      category: "文档",
      icon: "https://docs.taro.zone/img/logo-taro.png",
    },
    {
      title: "MySQL Docs",
      url: "https://dev.mysql.com/doc/refman/8.0/en/",
      category: "数据库",
      icon: "./icons/mysql-favicon.ico",
      Mark: true,
    },
    {
      title: "PostgreSQL Docs",
      url: "https://www.postgresql.org/docs/",
      category: "数据库",
      icon: "https://www.postgresql.org/favicon.ico",
      Mark: true,
    },
    {
      title: "Redis",
      url: "https://redis.io/",
      category: "数据库",
      icon: "https://redis.io/favicon.ico",
      Mark: true,
    },
    {
      title: "Elasticsearch",
      url: "https://www.elastic.co/elasticsearch",
      category: "数据库",
      icon: "https://www.elastic.co/icon-192.png",
      Mark: true,
    },
    {
      title: "MongoDB",
      url: "https://www.mongodb.com/zh-cn/docs/",
      category: "数据库",
      icon: "./icons/mongodb-favicon.ico",
      Mark: true,
    },
    {
      title: "Python Docs",
      url: "https://docs.python.org/zh-cn/3.9/c-api/index.html",
      category: "Python",
      icon: "https://docs.python.org/zh-cn/3.9/_static/py.svg",
      Mark: true,
    },
    {
      title: "PyPI",
      url: "https://pypi.org/",
      category: "Python",
      icon: "https://pypi.org/static/images/favicon.35549fe8.ico",
    },
    {
      title: "Angular Docs",
      url: "https://angular.cn/overview",
      category: "Angular",
      icon: "./icons/angular-favicon.ico",
    },
    {
      title: "Ngrx Docs",
      url: "https://ngrx.io/",
      category: "Angular",
      icon: "https://ngrx.io/favicon-32x32.png",
    },
    {
      title: "Material Docs",
      url: "https://material.angular.dev/",
      category: "Angular",
      icon: "https://material.angular.dev/assets/img/favicon.ico",
    },
    {
      title: "OpenResty",
      url: "https://openresty.org/cn/",
      category: "环境",
      icon: "https://openresty.org/favicon.ico",
      Mark: true,
    },
    {
      title: "Jenkins",
      url: "https://www.jenkins.io/",
      category: "环境",
      icon: "https://www.jenkins.io/favicon.ico",
      Mark: true,
    },
    {
      title: "宝塔面板",
      url: "https://www.bt.cn/new/index.html",
      category: "环境",
      icon: "./icons/bt-favicon.ico",
      Mark: true,
    },
    {
      title: "Three.js Docs",
      url: "https://techbrood.com/threejs/docs/",
      category: "Three.js",
      icon: "https://techbrood.com/favicon.ico",
    },
    {
      title: "Mobx-State-Tree",
      url: "https://mobx-state-tree.js.org/intro/welcome",
      category: "React",
      icon: "https://mobx-state-tree.js.org/img/favicon.ico",
    },
    {
      title: "D3.js 图形库",
      url: "https://d3-graph-gallery.com/all.html",
      category: "D3",
      icon: "",
    },
    {
      title: "ObservableHQ",
      url: "https://observablehq.com/top",
      category: "D3",
      icon: "./icons/observablehq-favicon.png",
      bgColor: "#ffffff",
    },
    {
      title: "D3.js 深度解析",
      url: "https://www.d3indepth.com/",
      category: "D3",
      icon: "./icons/d3indepth-favicon.png",
    },
    {
      title: "AntV G2",
      url: "https://g2.antv.antgroup.com/",
      category: "D3",
      icon: "./icons/g2-original.png",
    },
    {
      title: "Echarts",
      url: "https://echarts.apache.org/zh/index.html",
      category: "D3",
      icon: "https://echarts.apache.org/zh/images/favicon.png",
    },
    {
      title: "Element Plus",
      url: "https://element-plus.org/#/zh-CN",
      category: "Vue",
      icon: "https://element-plus.org/images/element-plus-logo-small.svg", // "https://element.eleme.cn/favicon.ico",
      Mark: true,
    },
    {
      title: "Ant Design",
      url: "https://ant-design.antgroup.com/index-cn",
      category: "React",
      icon: "./icons/antd-favicon.svg",
    },
    {
      title: "Axios",
      url: "https://axios-http.com/zh/",
      category: "文档",
      icon: "https://axios-http.com/assets/favicon.ico",
      Mark: true,
    },
    {
      title: "Sass",
      url: "https://www.sass.hk/",
      category: "文档",
      icon: "https://www.sass.hk/favicon.ico",
      Mark: true,
    },
    {
      title: "Less",
      url: "https://lesscss.org/",
      category: "文档",
      icon: "https://lesscss.org/public/ico/favicon.ico",
      Mark: true,
    },
    {
      title: "Tailwind CSS",
      url: "https://tailwindcss.com/",
      category: "文档",
      icon: "https://tailwindcss.com/favicons/favicon.ico",
      Mark: true,
    },
    {
      title: "Markdown",
      url: "https://markdown.com.cn/",
      category: "文档",
      icon: "https://markdown.com.cn/favicon.ico",
      bgColor: "#ffffff",
    },
    {
      title: "v0.app",
      url: "https://v0.app/",
      category: "文档",
      icon: "./icons/v0-favicon.svg",
      Mark: true,
    },
    {
      title: "LeetCode",
      url: "https://leetcode.cn/",
      category: "社区",
      icon: "https://leetcode.cn/favicon.ico",
      Mark: true,
    },
    {
      title: "Day.js",
      url: "https://day.js.org/zh-CN/",
      category: "文档",
      icon: "https://day.js.org/img/logo.png",
    },
    {
      title: "Mock.js",
      url: "http://mockjs.com/",
      category: "文档",
      icon: "./icons/mock-favicon.svg",
    },
    {
      title: "jQuery",
      url: "https://api.jquery.com/",
      category: "文档",
      icon: "./icons/jq-favicon.ico",
    },
    {
      title: "jQuery 中文文档",
      url: "http://caibaojian.com/jquery/",
      category: "文档",
      icon: "./icons/jqcn-favicon.ico",
    },
    {
      title: "Shadowsocks",
      url: "https://portal.shadowsocks.nz/",
      category: "VPN",
      icon: "https://portal.shadowsocks.nz/favicon.ico",
    },
    {
      title: "一元机场",
      url: "https://xn--1-q07a56pdss.com/#/profile",
      category: "VPN",
      icon: "https://xn--1-q07a56pdss.com/favicon.ico",
    },
    {
      title: "163 邮箱",
      url: "https://email.163.com/",
      category: "Email",
      icon: "https://email.163.com/favicon.ico",
    },
    {
      title: "QQ 邮箱",
      url: "https://mail.qq.com/",
      category: "Email",
      icon: "./icons/email.app.3c368bb.png",
    },
    {
      title: "阿里云企业邮箱",
      url: "https://qiye.aliyun.com/",
      category: "Email",
      icon: "./icons/aliyun-email-favicon.ico",
    },
    {
      title: "Gmail",
      url: "https://mail.google.com/",
      category: "Email",
      icon: "./icons/gmail.ico",
    },
    {
      title: "阿里云",
      url: "https://www.aliyun.com/",
      category: "Cloud",
      icon: "./icons/aliyun-32-32.ico",
    },
    {
      title: "腾讯云",
      url: "https://cloud.tencent.com/",
      category: "Cloud",
      icon: "https://cloud.tencent.com/favicon.ico",
    },
    {
      title: "有道云笔记",
      url: "https://note.youdao.com/",
      category: "笔记",
      icon: "https://note.youdao.com/favicon.ico",
    },
    {
      title: "Visual Studio Code",
      url: "https://code.visualstudio.com/",
      category: "IDE",
      icon: "https://code.visualstudio.com/assets/favicon.ico",
    },
    {
      title: "Cloud Copilot",
      url: "https://copilot.tencent.com/ide/",
      category: "IDE",
      icon: "./icons/copilot-logo.svg",
    },
    {
      title: "Cursor",
      url: "https://cursor.com/cn",
      category: "IDE",
      icon: "https://cursor.com/marketing-static/favicon.ico",
    },
    {
      title: "Trae",
      url: "https://www.trae.cn/",
      category: "IDE",
      icon: "./icons/trae-favicon.png",
    },
    {
      title: "CodeParrot",
      url: "https://codeparrot.ai/",
      category: "UI",
      icon: "https://codeparrot.ai/logo.svg",
    },
    {
      title: "Figma",
      url: "https://www.figma.com/",
      category: "UI",
      icon: "https://static.figma.com/app/icon/1/favicon.ico",
    },
    {
      title: "通义灵码",
      url: "https://lingma.aliyun.com/",
      category: "IDE",
      icon: "./icons/lingma.png",
    },
    {
      title: "Qodo",
      url: "https://www.qodo.ai/",
      category: "IDE",
      icon: "./icons/qodo-fav-32x32.webp",
    },
    {
      title: "Claude",
      url: "https://claude.com/",
      category: "IDE",
      icon: "./icons/claude-favicon.png",
    },
    {
      title: "Jest",
      url: "https://jestjs.io/",
      category: "文档",
      icon: "https://jestjs.io/img/favicon/favicon.ico",
    },
    {
      title: "即时设计",
      url: "https://js.design/",
      category: "UI",
      icon: "https://img.js.design/assets/webImg/favicon.ico",
    },
    {
      title: "Uizard",
      url: "https://app.uizard.io/",
      category: "UI",
      icon: "./icons/uizard-favicon-32x32.png",
    },
    {
      title: "Stitch",
      url: "https://stitch.withgoogle.com/",
      category: "UI",
      icon: "./icons/stitch-favicon-32x32.png",
    },
    {
      title: "墨刀",
      url: "https://modao.cc/brand",
      category: "UI",
      icon: "https://images.modao.cc/images/favicon.ico",
    },
    {
      title: "GitHub Copilot",
      url: "https://github.com/features/copilot",
      category: "IDE",
      icon: "./icons/copilot-favicon.svg",
    },
    {
      title: "IKuuu",
      url: "https://ikuuu.de/",
      category: "VPN",
      icon: "./icons/ikuuu-favicon.svg",
    },
    {
      title: "百度地图",
      url: "https://lbsyun.baidu.com/",
      category: "GIS",
      icon: "./icons/baidu-statics_logo_lbslogo_icon.ico",
    },
    {
      title: "高德地图",
      url: "https://lbs.amap.com/demo/list/js-api",
      category: "GIS",
      icon: "https://a.amap.com/pc/static/favicon.ico",
    },
    {
      title: "AntV L7",
      url: "https://l7.antv.antgroup.com/tutorial/quickstart",
      category: "GIS",
      icon: "./icons/g2-original.png",
    },
    {
      title: "Mapbox",
      url: "https://www.mapbox.com/",
      category: "GIS",
      icon: "./icons/mapbox_favicon_32x32.png",
    },
    {
      title: "Deck.gl",
      url: "https://deck.gl/",
      category: "GIS",
      icon: "./icons/geck.gl-favicon.ico",
    },
    {
      title: "React AMap",
      url: "https://elemefe.github.io/react-amap/",
      category: "GIS",
      icon: "./icons/el-map-favicon.png",
    },
    {
      title: "Natural Earth",
      url: "https://www.naturalearthdata.com/",
      category: "GIS",
      icon: "",
    },
    {
      title: "PM2",
      url: "https://pm2.io/docs/plus/overview/",
      category: "工具",
      icon: "https://pm2.io/favicon.ico",
      bgColor: "#ffffff",
    },
    {
      title: "Wireshark",
      url: "https://www.wireshark.org/",
      category: "工具",
      icon: "https://www.wireshark.org/favicon.ico",
    },
    {
      title: "Termius",
      url: "https://termius.com/index.html",
      category: "工具",
      icon: "./icons/termius-p7fs9iEFzckw8YZe84MoQfRQ.avif",
    },
    {
      title: "Postman",
      url: "https://www.postman.com/",
      category: "工具",
      icon: "./icons/postman-favicon.svg",
    },
    {
      title: "iTerm2",
      url: "https://iterm2.com/",
      category: "工具",
      icon: "https://iterm2.com/favicon.ico",
    },
    {
      title: "Oh My Zsh",
      url: "https://ohmyz.sh/",
      category: "工具",
      icon: "https://ohmyz.sh/favicon.ico",
    },
    {
      title: "Oh My Posh",
      url: "https://ohmyposh.dev/",
      category: "工具",
      icon: "https://ohmyposh.dev/img/favicons.svg",
    },
    {
      title: "Openvpn Connect",
      url: "https://openvpn.net/client/",
      category: "工具",
      icon: "./icons/openvpn-favicon.ico",
    },
    {
      title: "HexHub",
      url: "https://www.hexhub.cn/",
      category: "工具",
      icon: "https://www.hexhub.cn/favicon.ico",
    },
    {
      title: "Cherry AI",
      url: "https://www.cherry-ai.com/",
      category: "工具",
      icon: "./icons/cherry-favicon.png",
    },
    {
      title: "GitButler",
      url: "https://gitbutler.com/",
      category: "工具",
      icon: "https://gitbutler.com/favicon/favicon.svg",
    },
    {
      title: "Draw.io",
      url: "https://www.drawio.com/",
      category: "工具",
      icon: "https://www.drawio.com/favicon.ico",
    },
    {
      title: "SwitchHosts",
      url: "https://switchhosts.vercel.app/zh",
      category: "工具",
      icon: "./icons/switchhosts-favicon.ico",
    },
    {
      title: "Gitea",
      url: "https://about.gitea.com/",
      category: "工具",
      icon: "https://about.gitea.com/gitea.svg",
    },
    {
      title: "Babel",
      url: "https://www.babeljs.cn/",
      category: "文档",
      icon: "https://www.babeljs.cn/img/favicon.png",
    },
    {
      title: "MasterGo",
      url: "https://mastergo.com/",
      category: "工具",
      icon: "https://mastergo.com/favicon.ico",
    },
    {
      title: "菜鸟教程",
      url: "https://www.runoob.com/",
      category: "社区",
      icon: "./icons/runoob-favicon.ico",
    },
    {
      title: "W3Cschool",
      url: "https://www.w3cschool.cn/tutorial/",
      category: "社区",
      icon: "./icons/w3cschool-favicon.ico",
    },
    {
      title: "牛客网",
      url: "https://www.nowcoder.com/",
      category: "社区",
      icon: "./icons/nowcoderfavicon.ico",
    },
    {
      title: "Qoder",
      url: "https://qoder.com/",
      category: "IDE",
      icon: "./icons/qoder-favicon.svg",
    },
    {
      title: "Antigravity",
      url: "https://antigravity.google/",
      category: "IDE",
      icon: "./icons/antigravity-logo.png",
    },
    {
      title: "Hoppscotch",
      url: "https://hoppscotch.io/",
      category: "工具",
      icon: "./icons/hoppscotch-192x192.png",
    },
    {
      title: "Sublime Text",
      url: "https://www.sublimetext.com/",
      category: "IDE",
      icon: "https://www.sublimetext.com/favicon.ico",
    },
    {
      title: "GoAnother",
      url: "https://goanother.com/cn/",
      category: "工具",
      icon: "https://goanother.com/favicon.ico",
    },
    {
      title: "SourceTree",
      url: "https://www.sourcetreeapp.com/",
      category: "工具",
      icon: "./icons/sourcetree-favicon.ico",
    },
    {
      title: "HBuilderX",
      url: "https://www.dcloud.io/hbuilderx.html",
      category: "工具",
      icon: "https://hx.dcloud.net.cn/static/favicon/favicon.png",
    },
    {
      title: "Google Chrome",
      url: "https://www.google.cn/chrome/index.html",
      category: "工具",
      icon: "./icons/chrome-favicon-32x32.png",
    },
    {
      title: "Firefox",
      url: "https://www.firefox.com/zh-CN/",
      category: "工具",
      icon: "./icons/firefox-favicon.f093404c0135.ico",
    },
    {
      title: "Navicat",
      url: "https://www.navicat.com.cn/",
      category: "工具",
      icon: "./icons/Navicat_16_Premium_win_256x256.ico",
    },
    {
      title: "WPS",
      url: "https://platform.wps.cn/",
      category: "工具",
      icon: "./icons/wps-favicon.ico",
    },
    {
      title: "IntelliJ IDEA",
      url: "https://www.jetbrains.com/idea/download/",
      category: "IDE",
      icon: "./icons/Idea-Dark.svg",
    },
    {
      title: "DataGrip",
      url: "https://www.jetbrains.com/datagrip/download/",
      category: "IDE",
      icon: "https://www.jetbrains.com/favicon.ico",
    },
    {
      title: "PyCharm",
      url: "https://www.jetbrains.com/pycharm/download/",
      category: "IDE",
      icon: "./icons/PyCharm-Dark.svg",
    },
    {
      title: "CLion",
      url: "https://www.jetbrains.com/clion/download/",
      category: "IDE",
      icon: "./icons/CLion-Dark.svg",
    },
    {
      title: "GoLand",
      url: "https://www.jetbrains.com/go/download/",
      category: "IDE",
      icon: "https://www.jetbrains.com/favicon.ico",
    },
    {
      title: "WebStorm",
      url: "https://www.jetbrains.com/webstorm/download/",
      category: "IDE",
      icon: "./icons/WebStorm-Dark.svg",
    },
    {
      title: "Yarn",
      url: "https://yarnpkg.com/",
      category: "工具",
      icon: "https://yarnpkg.com/img/yarn-favicon.svg",
      Mark: true,
    },
    {
      title: "pnpm",
      url: "https://pnpm.io/zh/",
      category: "工具",
      icon: "https://pnpm.io/zh/img/favicon.png",
      Mark: true,
    },
    {
      title: "OPM",
      url: "https://opm.openresty.org/",
      category: "工具",
      icon: "https://openresty.org/favicon.ico",
    },
    {
      title: "MongoDB 中文社区",
      url: "https://mongoing.com/",
      category: "社区",
      icon: "./icons/mongoing-favicon.ico",
    },
    {
      title: "Moment.js",
      url: "https://momentjs.com/",
      category: "工具",
      icon: "./icons/moment-favicon.png",
    },
    {
      title: "Homebrew",
      url: "https://brew.sh/",
      category: "工具",
      icon: "https://brew.sh/assets/img/homebrew.svg",
    },
    {
      title: "Go 语言文档",
      url: "https://go.dev/learn/",
      category: "社区",
      icon: "https://go.dev/images/favicon-gopher.svg",
      Mark: true,
    },
    {
      title: "易语言",
      url: "https://www.dywt.com.cn/index.htm",
      category: "社区",
      icon: "https://www.dywt.com.cn/images/e.ico",
    },
    {
      title: "豆包",
      url: "https://www.doubao.com/chat/",
      category: "AI",
      icon: "https://lf-flow-web-cdn.doubao.com/obj/flow-doubao/doubao/chat/favicon.png",
    },
    {
      title: "Swagger",
      url: "https://swagger.io/",
      category: "工具",
      icon: "https://static1.smartbear.co/swagger/media/assets/swagger_fav.png",
      Mark: true,
    },
    {
      title: "SQL编辑器",
      url: "https://zhengjialux.github.io/Entry/SQLSyntax/",
      category: "工具",
      icon: "https://zhengjialux.github.io/Entry/SQLSyntax/favicon.svg",
    },
    {
      title: '英伟达开发者社区',
      url: 'https://build.nvidia.com/',
      category: "社区",
      icon: "https://build.nvidia.com/favicon.ico",
    },
    {
        title: 'Material UI',
        url: 'https://mui.com/material-ui/',
        category: "UI",
        icon: "https://mui.com/static/favicon.ico",
    },
    {
        title: '百度脑图',
        url: 'https://naotu.baidu.com/',
        category: "工具",
        icon: "https://naotu.baidu.com/favicon.ico",
    },
    {
        title: 'Glitch',
        url: 'https://blog.glitch.com/',
        category: "社区",
        icon: "https://blog.glitch.com/favicon.ico",
    },
    {
        title: 'FontAwesome',
        url: 'https://fontawesome.com/',
        category: "UI",
        icon: "https://fontawesome.com/favicon.ico",
    },
    {
        title: 'ES5 标准文档',
        url: 'https://www.w3.org/html/ig/zh/wiki/ES5',
        category: "文档",
        icon: "https://www.w3.org/favicon.ico",
    },
    {
        title: 'ECMA-262 小组',
        url: 'https://262.ecma-international.org/',
        category: "社区",
        icon: "https://262.ecma-international.org/img/ecma-logo.svg",
    },
    {
        title: 'UIverse',
        url: 'https://uiverse.io/',
        category: "UI",
        icon: "https://uiverse.io/favicon-32x32.png",
    },
    {
        title: 'Animista',
        url: 'https://animista.net/',
        category: "工具",
        icon: "https://animista.net/favicon.ico",
    },
    {
      title: 'Data Structure Visualizations',
      url: 'https://www.cs.usfca.edu/~galles/visualization/Algorithms.html',
      category: "工具",
      icon: "https://www.cs.usfca.edu/~galles/visualization/favicon.ico",
    },
    {
      title: 'VisuAlgo',
      url: 'https://visualgo.net/zh',
      category: "工具",
      icon: "https://visualgo.net/img/favicon.png",
    },
     {
      title: 'Algorithm Visualizer',
      url: 'https://algorithm-visualizer.org/',
      category: "工具",
      icon: "https://algorithm-visualizer.org/favicon.png",
    },
    {
      title: 'UnoCSS',
      url: 'https://unocss.dev/',
      category: "文档",
      icon: "https://unocss.dev/favicon.svg",
    },
    {
      title: 'Ant Design',
      url: 'https://ant-design.antgroup.com/index-cn',
      category: "UI",
      icon: "./icons/antd.svg",
    },
    {
      title: 'Pro Components',
      url: 'https://pro-components.antdigital.dev/',
      category: "UI",
      icon: "./icons/antd.svg",
    },
    {
      title: 'Antv L7',
      url: 'https://l7.antv.antgroup.com/zh',
      category: "UI",
      icon: "./icons/antv.png",
    },
    {
      title: 'Antv G6',
      url: 'https://g6.antv.antgroup.com/',
      category: "UI",
      icon: "./icons/antv.png",
    },
    {
      title: 'Antv F2',
      url: 'https://f2.antv.antgroup.com/',
      category: "UI",
      icon: "./icons/antv.png",
    },
    {
      title: 'Antv S2',
      url: 'https://s2.antv.antgroup.com/zh',
      category: "UI",
      icon: "./icons/antv.png",
    },
    {
      title: 'Antv X6',
      url: 'https://x6.antv.antgroup.com/',
      category: "UI",
      icon: "./icons/antv.png",
    },
    {
      title: 'L7 Editor',
      url: 'https://l7editor.antv.antgroup.com/',
      category: "工具",
      icon: "./icons/l7editor.ico",
    },
    {
      title: 'Ant Design Charts',
      url: 'https://ant-design-charts.antgroup.com/',
      category: "UI",
      icon: "./icons/antv.png",
    },
    {
      title: 'Highcharts 中文站',
      url: 'https://highcharts.com.cn/',
      category: "UI",
      icon: "https://highcharts.com.cn/favicon-32x32.png",
    },
    {
      title: 'Lodash',
      url: 'https://lodash.com/',
      category: "工具",
      icon: "https://lodash.com/assets/img/lodash.svg",
    },
    {
      title: 'Svelte',
      url: 'https://svelte.dev/',
      category: "工具",
      icon: "https://svelte.dev/favicon.png",
    },
    {
      title: 'Taro',
      url: 'https://docs.taro.zone/docs/',
      category: "跨终端框架",
      icon: "https://docs.taro.zone/img/icons/icon-144x144.png",
    },
    {
      title: 'VitePress',
      url: 'https://vitepress.dev/',
      category: "工具",
      icon: "https://vitepress.dev/vitepress-logo-mini.svg",
    },
    {
      title: 'Prettier',
      url: 'https://prettier.io/',
      category: "工具",
      icon: "https://prettier.io/icon.png",
      Mark: true,
    },
    {
      title: 'ESLint',
      url: 'https://eslint.org/',
      category: "工具",
      icon: "https://eslint.org/favicon.ico",
      Mark: true,
    },
    {
      title: 'Astro',
      url: 'https://astro.build/',
      category: "工具",
      icon: "https://astro.build/favicon.svg",
    },
    {
      title: 'Turborepo',
      url: 'https://turborepo.com/',
      category: "工具",
      icon: "./icons/turborepo.png",
    },
    {
      title: 'WebAssembly',
      url: 'https://webassembly.org/',
      category: "工具",
      icon: "https://webassembly.org/favicon.ico",
    },
    {
      title: 'Shadcn UI',
      url: 'https://ui.shadcn.com/',
      category: "工具",
      icon: "https://ui.shadcn.com/favicon.ico",
    },
    {
      title: 'Kafka',
      url: 'https://kafka.apache.org/',
      category: "工具",
      icon: "https://kafka.apache.org/images/apache.png",
      Mark: true,
    },
    {
      title: 'Tomcat',
      url: 'https://tomcat.apache.org/',
      category: "工具",
      icon: "https://tomcat.apache.org/favicon.ico",
    },
    {
      title: 'GraphQL',
      url: 'https://graphql.org/',
      category: "工具",
      icon: "https://graphql.org/favicon.ico",
      Mark: true,
    },
    {
      title: 'gRPC',
      url: 'https://grpc.io/',
      category: "工具",
      icon: "https://grpc.io/favicon.ico",
    },
    {
      title: 'etcd',
      url: 'https://etcd.io/',
      category: "工具",
      icon: "https://etcd.io/favicons/favicon.ico",
    },
    {
      title: 'Spring Boot',
      url: 'https://spring.io/projects/spring-boot',
      category: "工具",
      icon: "https://spring.io/favicon.svg",
      Mark: true,
    },
    {
      title: 'Kubernetes',
      url: 'https://kubernetes.io/',
      category: "工具",
      icon: "https://kubernetes.io/icons/favicon-32.png",
      Mark: true,
    },
    {
      title: 'Apache',
      url: 'https://www.apache.org/',
      category: "工具",
      icon: "https://www.apache.org/favicons/favicon.png",
    },
    {
      title: 'Subversion',
      url: 'https://subversion.apache.org/',
      category: "工具",
      icon: "https://subversion.apache.org/icon.png",
    },
    {
      title: 'Spring Framework',
      url: 'https://spring.io/projects/spring-framework',
      category: "工具",
      icon: "https://spring.io/favicon.svg",
      Mark: true,
    },
    {
      title: 'Dubbo',
      url: 'https://cn.dubbo.apache.org/zh-cn/',
      category: "工具",
      icon: "https://cn.dubbo.apache.org/imgs/favicon.png",
    },
    {
      title: 'Nacos',
      url: 'https://www.nacos.io/',
      category: "工具",
      icon: "https://www.nacos.io/favicon.ico",
    },
    {
      title: 'RabbitMQ',
      url: 'https://www.rabbitmq.com/',
      category: "工具",
      icon: "https://www.rabbitmq.com/img/rabbitmq-logo.svg",
    },
    {
      title: 'GitCode',
      url: 'https://gitcode.com/',
      category: "社区",
      icon: "https://cdn-static.gitcode.com/static/images/logo-favicon.png",
    },
    {
      title: 'Nifi',
      url: 'https://nifi.apache.org/',
      category: "工具",
      icon: "https://nifi.apache.org/images/apache-nifi-drop-logo.svg",
    },
    {
      title: 'DCloud',
      url: 'https://dev.dcloud.net.cn/',
      category: "社区",
      icon: "https://ask.dcloud.net.cn/static/css/classblack/img/favicon.png",
    },
    {
      title: 'Imaging',
      url: "https://products.aspose.app/imaging/conversion",
      category: "工具",
      icon: "https://products.aspose.app/imaging/shared/img/favicon.ico",
    },
    {
      title: 'Pencil',
      url: "https://www.pencil.dev/",
      category: "UI",
      icon: "https://www.pencil.dev/favicon.ico",
    },
    {
      title: 'Superdesign',
      url: 'https://app.superdesign.dev/',
      category: "UI",
      icon: "https://app.superdesign.dev/superdesign_logo.svg",
    },
    {
      title: 'Canva',
      url: 'https://www.canva.cn/',
      category: "UI",
      icon: "https://static.canva.cn/domain-assets/canva/static/images/favicon-1.ico",
    },
    {
      title: "styled-components",
      url: "https://styled-components.com/",
      category: "文档",
      icon: "https://styled-components.com/favicon.png",
    },
    {
      title: "Pug",
      url: "https://pugjs.org/",
      category: "文档",
      icon: "https://pugjs.org/images/favicon.ico",
    },
    {
      title: "Mongoose ODM",
      url: "https://mongoosejs.com/",
      category: "工具",
      icon: "https://mongoosejs.com/docs/images/favicon/favicon-32x32.png",
    },
    {
      title: "N8N",
      url: "https://n8n.io/",
      category: "工具",
      icon: "https://n8n.io/favicon.ico",
    },
    {
      title: "DataHub",
      url: "https://datahub.com/",
      category: "工具",
      icon: "./icons/dataHub-favicon.webp",
    },
    {
      title: "NPMX",
      url: "https://npmx.dev/",
      category: "社区",
      icon: "https://npmx.dev/favicon.svg",
    },
    {
      title: "NestJS",
      url: "https://nestjs.com/",
      category: "Node.js",
      icon: "./icons/nest-favicon.ico",
    },
    {
      title: "Hono",
      url: "https://hono.dev/",
      category: "Node.js",
      icon: "https://hono.dev/favicon.ico",
    },
    
    {
      title: "Quora",
      url: "https://www.quora.com/",
      category: "资讯",
      icon: "./icons/quora-favicon.ico",
    },
    {
      title: "Instagram",
      url: "https://www.instagram.com/",
      category: "资讯",
      icon: "./icons/instagram-favicon.ico",
    },
    {
      title: "Facebook",
      url: "https://www.facebook.com/",
      category: "资讯",
      icon: "./icons/facebook-favicon.ico",
    },
    {
      title: "OK",
      url: "https://ok.ru/",
      category: "资讯",
      icon: "https://ok.ru/favicon.svg",
    },
    {
      title: "VK",
      url: "https://vk.com/",
      category: "资讯",
      icon: "https://vk.com/images/icons/favicons/fav_logo.ico",
    },
    {
      title: "Discord",
      url: "https://discord.com/",
      category: "资讯",
      icon: "./icons/discord-favicon.png",
    },
    {
      title: "Pinterest",
      url: "https://www.pinterest.com/",
      category: "资讯",
      icon: "./icons/pinterest-favicon.png",
    },
    {
      title: "WhatsApp",
      url: "https://web.whatsapp.com/",
      category: "资讯",
      icon: "./icons/whatsapp-favicon.png",
    },
    {
      title: "Messenger",
      url: "https://www.messenger.com/",
      category: "资讯",
      icon: "./icons/messenger-favicon.ico",
    },
    {
      title: "OmeTV",
      url: "https://ome.tv/",
      category: "资讯",
      icon: "./icons/ometv-favicon.svg",
    },
    {
      title: "维基百科",
      url: "https://zh.wikipedia.org/wiki/Wikipedia:%E9%A6%96%E9%A1%B5",
      category: "资讯",
      icon: "https://zh.wikipedia.org/static/favicon/wikipedia.ico",
    },
    {
      title: "喜马拉雅",
      url: "https://studio.ximalaya.com/",
      category: "资讯",
      icon: "https://s1.xmcdn.com/lib/common/last/resource/1.0.0/icon/www/favicon.ico",
    },
    {
      title: "得到APP",
      url: "https://www.dedao.cn/",
      category: "资讯",
      icon: "https://www.dedao.cn/favicon.ico",
    },
    {
      title: "慕课网",
      url: "https://www.imooc.com/",
      category: "资讯",
      icon: "https://www.imooc.com/favicon.ico",
    },
    {
      title: "我要自学网",
      url: "https://www.51zxw.net/",
      category: "资讯",
      icon: "https://www.51zxw.net/favicon.ico",
    },
    {
      title: "沪江网校",
      url: "https://class.hujiang.com/",
      category: "资讯",
      icon: "https://res.hjfile.cn/classec/favicon.ico",
    }
  ],
  categoryIcons: {
    视频: "🎬",
    音乐: "🎵",
    工具: "🔧",
    其他: "📁",
    资讯: "📰",
    社区: "💬",
    环境: "🌍",
    文档: "📖",
    AI: "🤖",
    笔记: "📝",
    数据库: "🗄️",
    IDE: "💻",
    Python: "🐍",
    Angular: "🦄",
    跨终端框架: "🌐",
    Vue: "🍃",
    React: "⚛️",
    "Node.js": "🖥️",
    D3: "📊",
    "Three.js": "🧊",
    VPN: "🔒",
    Email: "📧",
    Cloud: "☁️",
    UI: "🎨",
    GIS: "🗺️",
    BOOK: "📚",
    Mark: "⭐",
  },
};











