const config = {
  // 个人信息
  me: {
    name: "Will/ZX",
    title: "全栈开发者 · 独立创作者",
    bio: "把想法写成代码，用代码方便现实",
    avatar: "https://avatars.githubusercontent.com/u/20078022?v=4",
    links: [
      {
        name: "GitHub",
        url: "https://github.com/zhengjialux",
        icon: "/icons/Github.svg",
      },
      {
        name: "Twitter",
        url: "https://twitter.com/kunsile16",
        icon: "/icons/Twitter.svg",
      },
      {
        name: "Email",
        url: "mailto:zhengjialu8507@gmail.com",
        icon: "/icons/Gmail.svg",
      },
    ],
  },
  // 项目数据
  works: [
    {
      title: "JPCodePlayground",
      desc: "代码在线调试。支持 JavaScript And Python",
      url: "https://github.com/OFEXJS/JPCodePlayground.git",
      icon: "JPCodePlayground.svg",
    },
    {
      title: "FundTabelTools",
      desc: "简单的报表统计可视化工具",
      url: "https://github.com/OFEXJS/FundTabelTools.git",
      icon: "FundTabelTools.svg",
    },
    {
      title: "dailyUI",
      desc: "日常开箱即用的UI组件",
      url: "https://github.com/OFEXJS/dailyUI.git",
    },
    {
      title: "Utility",
      desc: "日常使用的工具方法集合",
      url: "https://github.com/OFEXJS/Utility.git",
      cover: "",
    },
    {
      title: "lineage-datahub",
      desc: "抽离开源项目 DataHub 的血缘交互组件",
      url: "https://github.com/IDEADEMOX/lineage-datahub.git",
    },
    {
      title: "data-lineage-ui",
      desc: "抽离开源项目 open-mate-data 的数据血缘呈现组件",
      url: "https://github.com/IDEADEMOX/data-lineage-ui.git",
    },
  ],
  // 实例数据
  instances: [
    {
      id: 1,
      title: "代码在线编辑器",
      description: "支持 Javascript、Python 实时代码编辑和运行",
      tags: ["Javascript", "Python", "Node.js"],
      url: "/Entry/CodePlayground/",
      icon: "/icons/JPCodePlayground.svg",
      status: "online",
    },
    {
      id: 2,
      title: "SQL 语法在线测试工具",
      description: "测试 SQL 语法是否正确",
      tags: ["工具", "SQL", "在线开发"],
      url: "/Entry/SQLSyntax/",
      icon: "/icons/SQLSyntax.svg",
      status: "online",
    },
    {
      id: 3,
      title: "密钥百宝箱",
      description: "对密钥进行加解密，以及格式转换",
      tags: ["工具", "加密", "解密", "格式转换"],
      url: "/Entry/KeyPreview/",
      icon: "/icons/KeyPreview.svg",
      status: "online",
    },
    {
      id: 4,
      title: "图片处理工具",
      description: "对图片进行处理，例如转换、压缩等",
      tags: ["工具", "转换", "图片处理"],
      url: "/Entry/ImageAIProcessing/",
      icon: "/icons/ImageAIProcessing.png",
      status: "online",
    },
    {
      id: 5,
      title: "React 组件库",
      description: "展示各种可复用React UI组件示例",
      tags: ["React", "组件", "UI", "Typescript"],
      url: "/Entry/ExampleGalleryTR/",
      icon: "/icons/ExampleGalleryTR.svg",
      status: "updated",
    },
    {
      id: 6,
      title: "Vue 组件库",
      description: "展示各种可复用Vue UI组件示例",
      tags: ["Vue", "组件", "UI", "Typescript"],
      url: "/Entry/ExampleGalleryTV/",
      icon: "/icons/ExampleGalleryTV.svg",
      status: "updated",
    },
    {
      id: 7,
      title: "色彩面板",
      description: "颜色选择器，颜色值转换功能",
      tags: ["工具", "转换", "色彩取值"],
      url: "/Entry/ColorPanel/",
      icon: "/icons/ColorPanel.svg",
      status: "online",
    },
    {
      id: 8,
      title: "报表可视化分析工具",
      description: "交互式数据报表可视化分析工具",
      tags: ["数据可视化", "报表", "分析", "图表"],
      url: "",
      winDownloadUrl:
        "https://github.com/OFEXJS/FundTabelTools/releases/download/v1.0.0/fundtabeltools-Setup.exe",
      macDownloadUrl:
        "https://github.com/OFEXJS/FundTabelTools/releases/download/v1.0.0/fundtabeltools-mac-x64.zip",
      icon: "/icons/FundTabelTools.svg",
      status: "application",
    },
  ],
  // 文章数据
  articles: [
    {
      id: 1,
      title: "Never give up",
      excerpt: "Adhere to the law of quantitative and qualitative changes.",
      date: "2025-12-22",
      category: "励志",
      readTime: "20:15",
      url: "/blog/never-give-up.md",
    },
    {
      id: 2,
      title: "后端整体架构",
      excerpt: "理解前后端架构，理解从业务请求到返回数据的过程。",
      date: "2025-12-22",
      category: "node",
      readTime: "22:44",
      url: "/blog/node/note1.md",
    },
    {
      id: 3,
      title: "openresty 安装",
      excerpt: "搭建 openresty 开发环境。",
      date: "2025-12-30",
      category: "openresty",
      readTime: "14:16",
      url: "/blog/openresty/note1.md",
    },
    {
      id: 4,
      title: "第一个 openresty 程序",
      excerpt: "亲手启动一个 openresty 项目。",
      date: "2026-01-07",
      category: "openresty",
      readTime: "15:51",
      url: "/blog/openresty/note2.md",
    },
    {
      id: 5,
      title: "openresty 开发技巧",
      excerpt: "开发环境 openresty 开发技巧。",
      date: "2026-01-07",
      category: "openresty",
      readTime: "16:51",
      url: "/blog/openresty/note3.md",
    },
    {
      id: 6,
      title: "学习协议栈",
      excerpt: "对 OSI 模型、TCP/IP 模型有个基本认识。",
      date: "2026-01-08",
      category: "node",
      readTime: "20:37",
      url: "/blog/node/note2.md",
    },
    {
      id: 7,
      title: "速通 Docker",
      excerpt: "快速了解 Docker，上手 Docker 操作。",
      date: "2026-01-16",
      category: "docker",
      readTime: "14:45",
      url: "/blog/docker/note1.md",
    },
    {
      id: 8,
      title: "RESTful API",
      excerpt: "了解 HTTP 协议和 RESTful API 设计模式",
      date: "2026-01-17",
      category: "node",
      readTime: "14:22",
      url: "/blog/node/note3.md",
    },
    {
      id: 9,
      title: "初探 Node.js",
      excerpt: "了解 Node.js 的优势，并且手写第一个 Node 服务。",
      date: "2026-01-17",
      category: "node",
      readTime: "16:08",
      url: "/blog/node/note4.md",
    },
    {
      id: 10,
      title: "Node.js 事件循环机制",
      excerpt: "学习 Node.js 事件循环机制，理解其工作原理",
      date: "2026-01-17",
      category: "node",
      readTime: "23:38",
      url: "/blog/node/note5.md",
    },
    {
      id: 11,
      title: "Ubuntu 命令行",
      excerpt: "快速掌握服务器日常命令行操作",
      date: "2026-01-21",
      category: "linux",
      readTime: "19:24",
      url: "/blog/linux/note1.md",
    },
    {
      id: 12,
      title: "GIT/SVN 常用命令",
      excerpt: "日常项目版本管理的命令行参考",
      date: "2026-01-21",
      category: "linux",
      readTime: "20:25",
      url: "/blog/linux/note2.md",
    },
    {
      id: 13,
      title: "Ubuntu 目录结构说明",
      excerpt: "详细说明 Ubuntu 系统目录结构，供日常开发参考使用",
      date: "2026-01-22",
      category: "linux",
      readTime: "23:07",
      url: "/blog/linux/note3.md",
    },
    {
      id: 14,
      title: "Node.js 未来趋势",
      excerpt: "总结 Node 开发中的小知识",
      date: "2026-01-28",
      category: "node",
      readTime: "16:15",
      url: "/blog/node/note6.md",
    },
  ],
};
